### ISSUE TITLE
crash sorting names on some taxname tables

### ISSUE THREAD

**Issue by robert102** [Geo-omics/mibios#48]
```
glamr-webapp_1  | [2024-08-30 09:28:55,344] ERROR (django.request) pid:76279/140357757203520 Internal Server Error: /glamr/data/taxnode/2790
60/relations/children/  
glamr-webapp_1  | Traceback (most recent call last):
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
glamr-webapp_1  |     response = get_response(request)
glamr-webapp_1  |                ^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
glamr-webapp_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
glamr-webapp_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
glamr-webapp_1  |     return self.dispatch(request, *args, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 129, in dispatch
glamr-webapp_1  |     return super().dispatch(request, *args, cache=cache, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 57, in dispatch
glamr-webapp_1  |     return cache_page(300)(super().dispatch)(request, *args, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
glamr-webapp_1  |     response = view_func(request, *args, **kwargs)
glamr-webapp_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
glamr-webapp_1  |     return handler(request, *args, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 458, in get
glamr-webapp_1  |     return super().get(request, *args, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 137, in get
glamr-webapp_1  |     return super().get(request, *args, **kwargs)
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/views/generic/list.py", line 157, in get
glamr-webapp_1  |     context = self.get_context_data()
glamr-webapp_1  |               ^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 2017, in get_context_data
glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 470, in get_context_data
glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 621, in get_context_data
glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 251, in get_context_data
glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/glamr/views.py", line 62, in get_context_data

glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/local/lib/python3.11/dist-packages/mibios/views.py", line 101, in get_context_data
glamr-webapp_1  |     ctx = super().get_context_data(**ctx)
glamr-webapp_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django_tables2/views.py", line 146, in get_context_data
glamr-webapp_1  |     table = self.get_table(**self.get_table_kwargs())
glamr-webapp_1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django_tables2/views.py", line 106, in get_table
glamr-webapp_1  |     return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
glamr-webapp_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django_tables2/config.py", line 42, in configure
glamr-webapp_1  |     table.order_by = order_by
glamr-webapp_1  |     ^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django_tables2/tables.py", line 543, in order_by
glamr-webapp_1  |     self.data.order_by(self._order_by)
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django_tables2/data.py", line 226, in order_by
glamr-webapp_1  |     self.data = self.data.order_by(*order_by_accessors)
glamr-webapp_1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1149, in order_by
glamr-webapp_1  |     obj.query.add_ordering(*field_names)
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 2023, in add_ordering
glamr-webapp_1  |     self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
glamr-webapp_1  |   File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1569, in names_to_path
glamr-webapp_1  |     raise FieldError("Cannot resolve keyword '%s' into field. "
glamr-webapp_1  | django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: abundance, ancestors, children, 
citation, classified_uniref100, comments, contig, division, division_id, embl_code, gencode, gencode_id, has_specified_species, hidden_subtr
ee_root, host, hydro_gencode, hydro_gencode_id, id, is_div_inherited, is_genbank_hidden, is_gencode_inherited, is_hgc_inherited, is_mgc_inhe
rited, is_pgc_inherited, mergednodes, mito_gencode, mito_gencode_id, parent, parent_id, plastid_gencode, plastid_gencode_id, rank, rnacentra
l, taxid, taxname, taxnode, typematerial

```

**Comment by robert102** [comment]
Can't reproduce this anymore, I think it got resolved when the scientific name got added as field to the tax nodes.  Sorting both nodes and names in various ways seems to work now.
